name: release-delivery

on:
  push:
    tags:
      - 'v*'

env:
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:

  context:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.grep.outputs.name }}
      version: ${{ steps.grep.outputs.version }}
      sha: ${{ steps.grep.outputs.sha }}
      fqn: ${{ steps.grep.outputs.name }}-${{ steps.grep.outputs.version }}-${{ steps.grep.outputs.sha }}
      images: ${{ steps.docker_image_name.outputs.images }}

    steps:
      - uses: actions/checkout@v2

      - name: Grep project
        id: grep
        shell: bash
        run: |
          echo ::set-output name=name::$(head -n 5 pyproject.toml | grep name | cut -d ":" -f2 | grep -oP "(?<=\")([^\"]+)(?=\")")
          echo ::set-output name=cVer::$(head -n 5 pyproject.toml | grep version | cut -d ":" -f2 | grep -oP "(?<=\")([^\"]+)(?=\")")
          echo ::set-output name=version::$(echo "${{ github.ref }}" | sed -e "s#^refs/tags/v##")
          echo ::set-output name=sha::$(git rev-parse --short ${{ github.sha }})

      - name: Validate version
        id: validateVersion
        run: |
          echo "Should Validate Version with semantic..."
          echo "Project name: ${{ steps.grep.outputs.name }}"
          echo "Current version: ${{ steps.grep.outputs.cVer }}"
          echo "Target version: ${{ steps.grep.outputs.version }}"
          [[ ${{ steps.grep.outputs.cVer }} == ${{ steps.grep.outputs.version }} ]] || { echo "Release version and tag version is not match"; exit 1; }

      - name: Docker image name
        id: docker_image_name
        run: |
          localRegistry=localhost:5000/${{ steps.grep.outputs.name }}
          ghcr=ghcr.io/nubeio/${{ steps.grep.outputs.name }}
          dockerHub=nubeio/${{ steps.grep.outputs.name }}
          echo ::set-output name=images::$ghcr

  build:
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ needs.context.outputs.fqn }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ needs.context.outputs.name }}-

      - name: Build artifact by docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/build.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            BASE_IMAGE_VERSION=3.9
            APP_VERSION=${{ needs.context.outputs.version }}
            COMMIT_SHA=${{ needs.context.outputs.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          outputs: |
            type=local,dest=/tmp/images

      - name: Zip artifacts
        run: |
          mkdir -p /tmp/zip
          IFS=',' read -ra ARR <<< "${{ env.PLATFORMS }}"
          for plat in "${ARR[@]}"; do
            p=$(echo "${plat//\//}")
            p=$(echo "${p//linux/}")
            folder=$(echo "/tmp/images/${plat//\//_}/usr/src/app")
            cd $folder; zip -r /tmp/zip/${{ needs.context.outputs.fqn }}.$p.zip ./; cd -
          done

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ needs.context.outputs.images }}
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.NUBEIO_CI_GITHUBPACKAGE_TOKEN }}

      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/runtime.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            BASE_IMAGE_VERSION=3.9
            APP_VERSION=${{ needs.context.outputs.version }}
            COMMIT_SHA=${{ needs.context.outputs.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true

      - name: Create Release
        id: createRelease
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.context.outputs.version }}
          name: Release v${{ needs.context.outputs.version }}
          draft: false
          prerelease: false
          files: |
            /tmp/zip/${{ needs.context.outputs.fqn }}.*.zip
